# app/schemas/category.py

from pydantic import BaseModel

# --- Category Base Schema ---
# This schema contains fields that are common for both creation and output.
class CategoryBase(BaseModel):
    """
    Base schema for a product category, containing the category's name.
    """
    name: str

# --- Category Creation Schema ---
# This schema is used when an admin creates a new category.
# It inherits all fields from CategoryBase. In this case, it's just 'name'.
class CategoryCreate(CategoryBase):
    """
    Schema for creating a new category.
    """
    pass # No additional fields are needed for creation.

# --- Category Output Schema ---
# This schema defines the data that will be returned by the API when fetching a category.
# It includes the 'id' which is generated by the database.
class CategoryOut(CategoryBase):
    """
    Schema for data returned to the client. Includes the database-generated ID.
    """
    id: int

    # This configuration class enables the Pydantic model to be created
    # from an ORM object (like our SQLAlchemy Category model).
    class Config:
        from_attributes = True